[package]
name = "api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.11.1"
pretty_env_logger = "0.4.0"
serde = "1.0.130"
tokio = {version = "1.14.0", features = ["full"]}
warp = "0.3.2"
