[package]
name = "api"
version = "1.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
bollard = "0.11.1"
log = "0.4.14"
makepress-lib = { version = "3.0.0", registry = "makepress" }
pretty_env_logger = "0.4.0"
serde = "1.0.136"
sled = "0.34.7"
tokio = { version = "1.16.1", features = ["full"] }
warp = "0.3.2"
