version: 2.1

workflows:
  version: 2
  rust:
    jobs:
      - check:
          context: [aws]
      - build-and-deploy:
          context: [aws]
          requires:
            - check
jobs:
  check:
    executor: makepress-orb/rust
    steps:
      - checkout
      - makepress-orb/with-rust:
          steps:
            - run: |
                just check
                just test
  build-and-deploy:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          repo: makepress-api
          create-repo: true

orbs:
  makepress-orb: makepress/makepress-orb@2.0.0
  aws-ecr: circleci/aws-ecr@7.3.0
