version: 2.1

workflows:
  version: 2
  branch:
    jobs:
      - check:
          context: [aws]
      - test:
          context: [aws]
      - makepress-orb/release-please-single:
          context: [lulubot]
          filters:
            branches:
              only: main
      - build-and-publish-main:
          context: [aws]
          requires:
            - check
            - test
            - makepress-orb/release-please-single
          filters:
            branches:
              only:
                - main
  release:
    jobs:
      - build-and-publish-tagged:
          context: [aws]
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  check:
    executor: makepress-orb/rust
    steps:
      - checkout
      - makepress-orb/with-rust:
          steps:
            - run: cargo login --registry=makepress $KTRA_TOKEN
            - run: just check
  test:
    executor: makepress-orb/rust
    steps:
      - checkout
      - makepress-orb/with-rust:
          steps:
            - run: cargo login --registry=makepress $KTRA_TOKEN
            - run: just test
  build-and-publish-main:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: makepress-api
          create-repo: true
          setup-remote-docker: true
          remote-docker-layer-caching: true
  build-and-publish-tagged:
    docker:
      - image: cimg/base:2022.06
    steps:
      - aws-ecr/build-and-push-image:
          repo: makepress-api
          create-repo: true
          tag: ${CIRCLE_TAG/v/''}
          setup-remote-docker: true
          remote-docker-layer-caching: true

orbs:
  makepress-orb: makepress/makepress-orb@2.3.0
  aws-ecr: circleci/aws-ecr@8.0.0
